name: Serverless Computing
description: in der AWS Cloud
author: Niko Köbler

url: http://serverlessbuch.de
google_analytics:

social:
  email: info@serverlessbuch.de
  github: serverlessbuch
  twitter: serverlessbuch

links:
  amazon: https://www.amazon.de/gp/product/3868028072/ref=as_li_tl?ie=UTF8&tag=dasniko-21&camp=1638&creative=6742&linkCode=as2&creativeASIN=3868028072&linkId=45c0c27cc0563abcdf0e15ee179c4168
  entwickler: https://entwickler.de/?p=579804107

defaults:
  -
    scope:
      path: "" # emtpy means all files
      type: posts
    values:
      layout: post
      author: Niko Köbler

markdown: kramdown
#highlighter: rouge
permalink: /:year/:month/:title.html

sass:
  style: :compressed
#  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jemoji

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
